### PR TITLE
Add Http client metrics

### PR DESCRIPTION
**Pull request by ju-cu**
Add panels using HTTP client metrics (introduced in the Curity Identity Server 7.5.0)

### CODE REVIEW

**Comment by travisspencer** [comment]
What happens if this version of Grafana is used with an older version of Curity that doesn't support HTTP metrics? Just an empty widget in the dashboard?

**Comment by ju-cu** [comment]
Yes, if there's no data, the panel will be empty and have the header ("none").

**Comment by ClaudenirFreitas** [comment]
@ju-cu one question, 
I just tested with 2 HTTP clients:

Screenshot 2022-11-10 at 13 17 19

 The title should be generic because it shows only one HTTP Client.

Screenshot 2022-11-10 at 13 18 12

Please, correct me if I am wrong.

Thanks for updating these dashboards, they are critical to us.

**Comment by ju-cu** [comment]
That's not intended. I'll investigate.

**Comment by ju-cu** [comment]
Seems like the repeat feature does not work for variables that do not have the "all"-flag enabled so I reverted the last commit. This means that when using this dashboard with older versions of the Curity Identity Server, the panel will still be empty but will have "All" in the title which is not very nice.

**Comment by ClaudenirFreitas** [comment]
Cool, it's working now. 

Thanks @ju-cu!

**Comment by ju-cu** [comment]
> Cool, it's working now.
> 
> Thanks @ju-cu!

No worries! Thanks for testing. I wait for a formal approval for this PR and will merge it at the beginning of next week. Then we will make a new revision available on grafana.com as well.

**Review by gary-archer — APPROVED** [review]
This all looks OK as long as there are no backwards compatibility problems, which now seem to have been resolved.

**Pull request merged**
